package indieshop.entities;
// Generated 12-12-2020 04:09:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaProductos generated by hbm2java
 */
@Entity
@Table(name="categoria_productos"
    ,catalog="indie_shop"
)
public class CategoriaProductos  implements java.io.Serializable {


     private String idCat;
     private String nomCat;
     private String desCat;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public CategoriaProductos() {
    }

	
    public CategoriaProductos(String idCat) {
        this.idCat = idCat;
    }
    public CategoriaProductos(String idCat, String nomCat, String desCat, Set<Productos> productoses) {
       this.idCat = idCat;
       this.nomCat = nomCat;
       this.desCat = desCat;
       this.productoses = productoses;
    }
   
     @Id 

    
    @Column(name="id_cat", unique=true, nullable=false, length=10)
    public String getIdCat() {
        return this.idCat;
    }
    
    public void setIdCat(String idCat) {
        this.idCat = idCat;
    }

    
    @Column(name="nom_cat", length=100)
    public String getNomCat() {
        return this.nomCat;
    }
    
    public void setNomCat(String nomCat) {
        this.nomCat = nomCat;
    }

    
    @Column(name="des_cat", length=100)
    public String getDesCat() {
        return this.desCat;
    }
    
    public void setDesCat(String desCat) {
        this.desCat = desCat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoriaProductos")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


