package indieshop.entities;
// Generated 12-12-2020 04:09:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="productos"
    ,catalog="indie_shop"
)
public class Productos  implements java.io.Serializable {


     private String idPro;
     private CategoriaProductos categoriaProductos;
     private Proveedores proveedores;
     private String nomPro;
     private String desLib;
     private Double precioPro;
     private Integer exiPro;
     private Set<ProductosFactura> productosFacturas = new HashSet<ProductosFactura>(0);

    public Productos() {
    }

	
    public Productos(String idPro) {
        this.idPro = idPro;
    }
    public Productos(String idPro, CategoriaProductos categoriaProductos, Proveedores proveedores, String nomPro, String desLib, Double precioPro, Integer exiPro, Set<ProductosFactura> productosFacturas) {
       this.idPro = idPro;
       this.categoriaProductos = categoriaProductos;
       this.proveedores = proveedores;
       this.nomPro = nomPro;
       this.desLib = desLib;
       this.precioPro = precioPro;
       this.exiPro = exiPro;
       this.productosFacturas = productosFacturas;
    }
   
     @Id 

    
    @Column(name="id_pro", unique=true, nullable=false, length=10)
    public String getIdPro() {
        return this.idPro;
    }
    
    public void setIdPro(String idPro) {
        this.idPro = idPro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cat")
    public CategoriaProductos getCategoriaProductos() {
        return this.categoriaProductos;
    }
    
    public void setCategoriaProductos(CategoriaProductos categoriaProductos) {
        this.categoriaProductos = categoriaProductos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_prov")
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }

    
    @Column(name="nom_pro", length=100)
    public String getNomPro() {
        return this.nomPro;
    }
    
    public void setNomPro(String nomPro) {
        this.nomPro = nomPro;
    }

    
    @Column(name="des_lib", length=100)
    public String getDesLib() {
        return this.desLib;
    }
    
    public void setDesLib(String desLib) {
        this.desLib = desLib;
    }

    
    @Column(name="precio_pro", precision=22, scale=0)
    public Double getPrecioPro() {
        return this.precioPro;
    }
    
    public void setPrecioPro(Double precioPro) {
        this.precioPro = precioPro;
    }

    
    @Column(name="exi_pro")
    public Integer getExiPro() {
        return this.exiPro;
    }
    
    public void setExiPro(Integer exiPro) {
        this.exiPro = exiPro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productos")
    public Set<ProductosFactura> getProductosFacturas() {
        return this.productosFacturas;
    }
    
    public void setProductosFacturas(Set<ProductosFactura> productosFacturas) {
        this.productosFacturas = productosFacturas;
    }




}


