package indieshop.entities;
// Generated 12-13-2020 12:54:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductosFactura generated by hbm2java
 */
@Entity
@Table(name="productos_factura"
    ,catalog="indie_shop"
)
public class ProductosFactura  implements java.io.Serializable {


     private String idPfac;
     private Facturacion facturacion;
     private Productos productos;
     private Integer cantidadPfac;
     private Double totPfac;

    public ProductosFactura() {
    }

	
    public ProductosFactura(String idPfac) {
        this.idPfac = idPfac;
    }
    public ProductosFactura(String idPfac, Facturacion facturacion, Productos productos, Integer cantidadPfac, Double totPfac) {
       this.idPfac = idPfac;
       this.facturacion = facturacion;
       this.productos = productos;
       this.cantidadPfac = cantidadPfac;
       this.totPfac = totPfac;
    }
   
     @Id 

    
    @Column(name="id_pfac", unique=true, nullable=false, length=10)
    public String getIdPfac() {
        return this.idPfac;
    }
    
    public void setIdPfac(String idPfac) {
        this.idPfac = idPfac;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fac")
    public Facturacion getFacturacion() {
        return this.facturacion;
    }
    
    public void setFacturacion(Facturacion facturacion) {
        this.facturacion = facturacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pro")
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    
    @Column(name="cantidad_pfac")
    public Integer getCantidadPfac() {
        return this.cantidadPfac;
    }
    
    public void setCantidadPfac(Integer cantidadPfac) {
        this.cantidadPfac = cantidadPfac;
    }

    
    @Column(name="tot_pfac", precision=22, scale=0)
    public Double getTotPfac() {
        return this.totPfac;
    }
    
    public void setTotPfac(Double totPfac) {
        this.totPfac = totPfac;
    }




}


