package indieshop.entities;
// Generated Dec 13, 2020 5:51:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedores generated by hbm2java
 */
@Entity
@Table(name="proveedores"
    ,catalog="indie_shop"
)
public class Proveedores  implements java.io.Serializable {


     private String idProv;
     private String nomProv;
     private String corProv;
     private String dirProv;
     private String telProv;
     private Integer numVenProv;
     private Set<Productos> productoses = new HashSet<Productos>(0);
     private Set<Valoracion> valoracions = new HashSet<Valoracion>(0);

    public Proveedores() {
    }

	
    public Proveedores(String idProv) {
        this.idProv = idProv;
    }
    public Proveedores(String idProv, String nomProv, String corProv, String dirProv, String telProv, Integer numVenProv, Set<Productos> productoses, Set<Valoracion> valoracions) {
       this.idProv = idProv;
       this.nomProv = nomProv;
       this.corProv = corProv;
       this.dirProv = dirProv;
       this.telProv = telProv;
       this.numVenProv = numVenProv;
       this.productoses = productoses;
       this.valoracions = valoracions;
    }
   
     @Id 

    
    @Column(name="id_prov", unique=true, nullable=false, length=10)
    public String getIdProv() {
        return this.idProv;
    }
    
    public void setIdProv(String idProv) {
        this.idProv = idProv;
    }

    
    @Column(name="nom_prov", length=100)
    public String getNomProv() {
        return this.nomProv;
    }
    
    public void setNomProv(String nomProv) {
        this.nomProv = nomProv;
    }

    
    @Column(name="cor_prov", length=100)
    public String getCorProv() {
        return this.corProv;
    }
    
    public void setCorProv(String corProv) {
        this.corProv = corProv;
    }

    
    @Column(name="dir_prov", length=100)
    public String getDirProv() {
        return this.dirProv;
    }
    
    public void setDirProv(String dirProv) {
        this.dirProv = dirProv;
    }

    
    @Column(name="tel_prov", length=15)
    public String getTelProv() {
        return this.telProv;
    }
    
    public void setTelProv(String telProv) {
        this.telProv = telProv;
    }

    
    @Column(name="num_ven_prov")
    public Integer getNumVenProv() {
        return this.numVenProv;
    }
    
    public void setNumVenProv(Integer numVenProv) {
        this.numVenProv = numVenProv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedores")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedores")
    public Set<Valoracion> getValoracions() {
        return this.valoracions;
    }
    
    public void setValoracions(Set<Valoracion> valoracions) {
        this.valoracions = valoracions;
    }




}


