package indieshop.entities;
// Generated Dec 13, 2020 5:51:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposUsuarios generated by hbm2java
 */
@Entity
@Table(name="tipos_usuarios"
    ,catalog="indie_shop"
)
public class TiposUsuarios  implements java.io.Serializable {


     private String idTu;
     private String rolTu;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public TiposUsuarios() {
    }

	
    public TiposUsuarios(String idTu) {
        this.idTu = idTu;
    }
    public TiposUsuarios(String idTu, String rolTu, Set<Usuarios> usuarioses) {
       this.idTu = idTu;
       this.rolTu = rolTu;
       this.usuarioses = usuarioses;
    }
   
     @Id 

    
    @Column(name="id_tu", unique=true, nullable=false, length=10)
    public String getIdTu() {
        return this.idTu;
    }
    
    public void setIdTu(String idTu) {
        this.idTu = idTu;
    }

    
    @Column(name="rol_tu", length=50)
    public String getRolTu() {
        return this.rolTu;
    }
    
    public void setRolTu(String rolTu) {
        this.rolTu = rolTu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposUsuarios")
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


