package indieshop.entities;
// Generated 12-12-2020 04:09:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="indie_shop"
)
public class Usuarios  implements java.io.Serializable {


     private String idUs;
     private String nomUs;
     private String apeUs;
     private String nicUs;
     private String passUs;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public Usuarios() {
    }

	
    public Usuarios(String idUs) {
        this.idUs = idUs;
    }
    public Usuarios(String idUs, String nomUs, String apeUs, String nicUs, String passUs, Set<Clientes> clienteses) {
       this.idUs = idUs;
       this.nomUs = nomUs;
       this.apeUs = apeUs;
       this.nicUs = nicUs;
       this.passUs = passUs;
       this.clienteses = clienteses;
    }
   
     @Id 

    
    @Column(name="id_us", unique=true, nullable=false, length=10)
    public String getIdUs() {
        return this.idUs;
    }
    
    public void setIdUs(String idUs) {
        this.idUs = idUs;
    }

    
    @Column(name="nom_us", length=100)
    public String getNomUs() {
        return this.nomUs;
    }
    
    public void setNomUs(String nomUs) {
        this.nomUs = nomUs;
    }

    
    @Column(name="ape_us", length=100)
    public String getApeUs() {
        return this.apeUs;
    }
    
    public void setApeUs(String apeUs) {
        this.apeUs = apeUs;
    }

    
    @Column(name="nic_us", length=100)
    public String getNicUs() {
        return this.nicUs;
    }
    
    public void setNicUs(String nicUs) {
        this.nicUs = nicUs;
    }

    
    @Column(name="pass_us", length=100)
    public String getPassUs() {
        return this.passUs;
    }
    
    public void setPassUs(String passUs) {
        this.passUs = passUs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


