package indieshop.entities;
// Generated 12-13-2020 12:54:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Valoracion generated by hbm2java
 */
@Entity
@Table(name="valoracion"
    ,catalog="indie_shop"
)
public class Valoracion  implements java.io.Serializable {


     private String idVal;
     private Clientes clientes;
     private Proveedores proveedores;
     private Double calVal;
     private String comVal;

    public Valoracion() {
    }

	
    public Valoracion(String idVal) {
        this.idVal = idVal;
    }
    public Valoracion(String idVal, Clientes clientes, Proveedores proveedores, Double calVal, String comVal) {
       this.idVal = idVal;
       this.clientes = clientes;
       this.proveedores = proveedores;
       this.calVal = calVal;
       this.comVal = comVal;
    }
   
     @Id 

    
    @Column(name="id_val", unique=true, nullable=false, length=10)
    public String getIdVal() {
        return this.idVal;
    }
    
    public void setIdVal(String idVal) {
        this.idVal = idVal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cli")
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_prov")
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }

    
    @Column(name="cal_val", precision=22, scale=0)
    public Double getCalVal() {
        return this.calVal;
    }
    
    public void setCalVal(Double calVal) {
        this.calVal = calVal;
    }

    
    @Column(name="com_val", length=100)
    public String getComVal() {
        return this.comVal;
    }
    
    public void setComVal(String comVal) {
        this.comVal = comVal;
    }




}


